services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: calculator-frontend
    ports:
      - "80:3000"
    volumes:
      - ./frontend:/app
      - ./frontend/node_modules:/app/node_modules
      - ./frontend/build:/app/build
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start
    networks:
      - calculator-network
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: calculator-backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - ./backend/app/tmp:/app/tmp
    networks:
      - calculator-network
networks:
  calculator-network:
    driver: bridge